version: '3.8'
services:
    db:
        container_name: mysql_db
        image: mysql
        restart: unless-stopped
        env_file: ./.env
        ports:
        - 3336:3306
        environment:
        - MYSQL_ROOT_PASSWORD=user
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
        - MYSQL_DATABASE=demodb
        volumes:
        - "./var/lib/mysql"
